on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEVOPSELLENCE_ENV_VARS: ${{ vars.DEVOPSELLENCE_ENV_VARS }}
      DEVOPSELLENCE_SECRETS: ${{ secrets.DEVOPSELLENCE_SECRETS }}
    steps:
      - uses: actions/checkout@v4
      - uses: devopsellence/deploy-action@v1
        with:
          token: ${{ secrets.DEVOPSELLENCE_TOKEN }}
          organization: default
          project: github-actions-demo
          environment: production
